export const Sticker = [

    { id: 1, img: require('./sticker/img1.png') },
    { id: 2, img: require('./sticker/img2.png') },
    { id: 3, img: require('./sticker/img3.png') },
    { id: 4, img: require('./sticker/img4.png') },
    { id: 5, img: require('./sticker/img5.png') },
    { id: 6, img: require('./sticker/img6.png') },
    { id: 7, img: require('./sticker/img7.png') },
    { id: 8, img: require('./sticker/img8.png') },
    { id: 9, img: require('./sticker/img9.png') },
    { id: 10, img: require('./sticker/img10.png') },
    { id: 11, img: require('./sticker/img11.png') },
    { id: 12, img: require('./sticker/img12.png') },
    { id: 13, img: require('./sticker/img13.png') },
    { id: 14, img: require('./sticker/img14.png') },
    { id: 15, img: require('./sticker/img15.png') },
    { id: 16, img: require('./sticker/img16.png') },
    { id: 17, img: require('./sticker/img17.png') },
    { id: 18, img: require('./sticker/img18.png') },
    { id: 19, img: require('./sticker/img19.png') },
    { id: 20, img: require('./sticker/img20.png') },
    { id: 21, img: require('./sticker/img21.png') },
    { id: 22, img: require('./sticker/img22.png') },
    { id: 23, img: require('./sticker/img23.png') },
    { id: 24, img: require('./sticker/img24.png') },
    { id: 25, img: require('./sticker/img25.png') },
    { id: 26, img: require('./sticker/img26.png') },
    { id: 27, img: require('./sticker/img27.png') },
    { id: 28, img: require('./sticker/img28.png') },
    { id: 29, img: require('./sticker/img29.png') },
];